### ISSUE TITLE
Volume of the controller

### ISSUE THREAD

**Issue by 7heS4ge** [horseyhorsey/PinGod.VP#2]
Hi,
I don't find a way to reduce the volume of the backglass screen, the music is louder than sound effects of Visual Pinball.
I have the same problem with Pup-Pack, I reduce the volume at 40% for all pup-packs.

Maybe in the settings of the controller in the Visual Pinball script ? :
With Controller
	.Volume = 40 '0 to 100

**Comment by horseyhorsey** [comment]
In the `settings.save` you can change the music and master volume. You have to use minus decibel, like `-6`

**Comment by 7heS4ge** [comment]
Wonderful ! Yes it works, thank you.

**Comment by horseyhorsey** [comment]
That's great. It should be in every games service menu but I just haven't had any need for that yet.

**Comment by horseyhorsey** [comment]
> Wonderful ! Yes it works, thank you.

These changes will solve volume and adjusting files manually. Cheers.

![image](https://user-images.githubusercontent.com/5377332/148056222-1812b8c7-4e68-4a9e-94cf-751c265bcc38.png)

**Comment by 7heS4ge** [comment]
Great. But where is this menu ? It's the service menu displayed with the key 0 ? In which table ?
Remark : I tested the source code on godot by following the documentation on https://blog.flippingflips.com, and it's very convenient.

**Comment by horseyhorsey** [comment]
> Great. But where is this menu ? It's the service menu displayed with the key 0 ? In which table ? Remark : I tested the source code on godot by following the documentation on https://blog.flippingflips.com, and it's very convenient.

Cool well done. The blog's probably going out of date, thanks for reminding me, glad it helped. There are docs in the examples but they could also be updated.
